#!/bin/bash

read class label template vcpus memory netvm

/usr/bin/qvm-create --class ${class} --label ${label} --template ${template} --property vcpus=${vcpus} --property memory=${memory} --property netvm=${netvm} $1
/usr/bin/qvm-tags $1 add vagrant
